package com.example.androidmvpbase.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.androidmvpbase.db.dbBean.DbPerson;

import com.example.androidmvpbase.db.greendao.DbPersonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbPersonDaoConfig;

    private final DbPersonDao dbPersonDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbPersonDaoConfig = daoConfigMap.get(DbPersonDao.class).clone();
        dbPersonDaoConfig.initIdentityScope(type);

        dbPersonDao = new DbPersonDao(dbPersonDaoConfig, this);

        registerDao(DbPerson.class, dbPersonDao);
    }
    
    public void clear() {
        dbPersonDaoConfig.clearIdentityScope();
    }

    public DbPersonDao getDbPersonDao() {
        return dbPersonDao;
    }

}
